Definición de milestones iniciales en forma de PMVs
jlgallego99/TropesToGo pull request #25
Opened 2023-03-02 19:09 UTC by jlgallego99

Se definen los milestones iniciales, añadiendo nuevos milestones y abordando los problemas #18 #19 #20. Ahora se tiene un milestone enfocado a la modelización del problema antes de empezar con el desarrollo, que se centrará primero en hacer el scraper solo para películas y luego en desarrollar la aplicación de línea de comandos donde el usuario tendrá opciones sobre qué contenidos quiere #7. También se tiene un nuevo milestone enfocado en extraer la información no estructurada para poder relacionar con IMDB #8

2023-03-02 19:17 UTC, JJ requested changes
El obstáculo principal es la secuenciación de los milestones, repiénsatela.
Por otro lado, recuerda que los milestones incluyen entregables, así que tendrás que hacer release en cada milestone y enlazarlos desde el PDF según los vayas produciendo.

2023-03-02 19:17 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection{M5. Integración con IMDB y extracción de metadatos}
Formúlalo como el producto que quieres: conseguir identificar qué peli en IMDB corresponde a la que hay en Tvtropes.
En todo caso, yo no planificaría tanto. Ten en cuenta que puede que al final no trates sólo con pelis; pueden ser libros (que tiene goodreads) o juegos (que no sé lo que tiene)

2023-03-02 19:17 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection{M6. Extracción de tropos de videojuegos, libros y series}
Esto yo creo que sería anterior al 5. Piensa que tienes que secuenciarlos de forma que en cada momento tengas lo que necesitas; después del 4 puede ir este perfectamente, y este sí es imprescindible para llegar a la herramienta de línea de órdenes.

2023-03-02 19:17 UTC, JJ commented on doc/secciones/04_planificacion.tex
>  \subsection{Desarrollo dirigido por pruebas}
No forma parte de este PR, pero quizás convendría que replantearas un poco todo esto. Las pruebas son parte integral del desarrollo ágil; si vas a escribir las pruebas _antes_ que el código, entonces sí estás hablando de TDD, pero no sé si es el caso o no.

2023-03-04 18:35 UTC, jlgallego99 commented
He replanteado los milestones de forma que primero se desarrolle todo el scraper como tal (primero solo para pelis, luego para el resto), luego se desarrolle la propia aplicación CMD con el scraper ya hecho y luego se refine más lo que ya se tiene, primero haciendo que los datos se actualicen periódicamente y luego haciendo que se pueda relacionar con IMDB y otras fuentes de datos del estilo (no especificando cuales exactamente)
En los commits he hecho referencia a otro PR sin querer

2023-03-06 10:38 UTC, JJ requested changes
Está bastante mejor que el anterior, pero yo creo que deberías plantearte los milestones más en el dominio del problema que de la aplicación. Recuerda las diferentes fases del scraping: 
1. Hallar el URL
2. Entender/testear la estructura (incluyendo si ha habido modificaciones)
3. Extraer la información
4. Almacenar

Esto es *para una sola página*. Ya implica una serie de problemas en sí. Por eso tendrías que pensar en las dos partes de la aplicación: el scraper (que extra información de una página) y la "araña" (que recorre el sitio). En principio son (más o menos) independientes. El segundo es esencial, el primero puede hacerse en un PMV más o menos a mano.
Pero los dos son esenciales para hacer el actualizador; al final el actualizador lo que haría sería lanzar la araña a ver si hay nuevas páginas y una vez encontradas, descargarlas (junto con actualizaciones de las antiguas)
Así que, por favor, dale una vuelta a los milestones que reflejen un poco productos que sean capaces de tener encuenta esta estructura del problema y sus interdependencias.

2023-03-06 10:38 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Los hitos o milestones representan cada uno de los estados en los que va a ir evolucionando la aplicación, conformando un Producto Mínimamente Viable. Cada PMV se construye encima de los anteriores,
Conviene, sobre todo en TFMs, que apoyes la parte de la metodología con algún artículo o libro. Busca alguno que te venga bien, y cítalo en esta parte. Recuerda que no todo el mundo conoce la metodología ágil (o, para el caso, la metodología de desarrollo en ingeniería de software)

2023-03-06 10:38 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Un milestone se considerará como completado una vez se hayan resuelto todas sus tareas asociadas, o issues de GitHub, y al terminarlo y subir sus cambios a la rama principal (tras un pull request que
Las buenas prácticas ponen las palabras de idioma extranjero en cursiva.

2023-03-06 10:38 UTC, JJ commented on doc/secciones/04_planificacion.tex
>  \subsubsection{M0. Configuración inicial - Objetivos, metodología e infraestructura}
Quizás añadir, aquí o en el texto, "infraestructura de control de calidad".
Recuerda que
1. La calidad es una de las rúbricas que se evalúan en el TFG (o sea, #1 )
2. También es una de las preocupaciones principales en el desarrollo ágil.

2023-03-06 10:38 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection{M3. Extracción de tropos de videojuegos, libros y series}
Yo de veras que secuenciaría esto al final (o sea, después de que leas el TFM).

2023-03-06 20:35 UTC, jlgallego99 commented
He centrado los hitos en el dominio del problema, dividiéndolos un poco más en base a lo que se ahora, pero especificando que van surgiendo conforme se va trabajando
Tambien he empezado a desarrollar mejor la parte de la metodología, con nuevas referencias, pero quizá eso mejor revisarlo en otro PR ya con todo el capitulo?

2023-03-07 06:59 UTC, JJ approved these changes
Sólo objeciones menores.

2023-03-07 06:59 UTC, JJ commented on doc/bibliografia.bib
> +@article{abrahamsson2017agile,
Creo que ArXiV genera automáticamente los .bib, incluyendo el URL.

2023-03-07 06:59 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item Para llevar el seguimiento de las historias de usuario y tareas asociadas a ellas de la metodología de desarrollo ágil se han creado una serie de \textit{issues} o tareas en el repositorio
Los issues no son tareas, son problemas. Yo lo dejaría sin traducir.

2023-03-07 06:59 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection{M6. Extracción de tropos de videojuegos, libros y series}
O posterior al 7. En todo caso, ¿te parece que cierra el siguiente? Si no es así, ponlo a continuación.

2023-03-07 17:43 UTC, merged