Inclusión y justificación del gestor de tareas
jlgallego99/TropesToGo pull request #27
Opened 2023-03-06 20:07 UTC by jlgallego99

Se analizan varias alternativas para un gestor de tareas del proyecto, comentando sus ventajas y desventajas, y se decide cual de ellas se elige #26 

closes #13

2023-03-07 06:53 UTC, JJ requested changes
El principal problema es que hay muchos cambios que no se corresponden al objeto del PR; de los específicos, conviene que reorganices la justificación de la elección del gestor de tareas. Recuerda que lo importante es que #1 vea que sigues una metodología adecuada para hacerlo, no tanto lo que elijas. Y en todo caso `mask` es bastante menos conocido que `make`, así que tienes que justificarlo bien.

2023-03-07 06:53 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Los hitos o milestones representan cada uno de los estados en los que va a ir evolucionando la aplicación, conformando un Producto Mínimamente Viable. Cada PMV se construye encima de los anteriores,
REcuerda la bibliografía y que #1 no tiene por qué conocer estos conceptos.

2023-03-07 06:53 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +En este primer hito se pretende abordar toda la planificación inicial y preparación del proyecto. Como producto al final de este hito se definirán los hitos iniciales del proyecto y se tendrán escrit
Enlaza también el milestone en el repo.
Por otro lado, trabajar con líneas así provoca todo tipo de problemas a la hora de corregir. Voy a abrir un issue para eso.

2023-03-07 06:53 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Al hablar de gestores de tareas el primero en el que se suele pensar es en \textit{make}, el cual es una herramienta muy utilizada en cualquier ámbito de la informática. Sin embargo, se ha optado por
Si es el primero, menciónalo el primero.

2023-03-07 06:53 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Dentro de los procesos de calidad del software entran los gestores de tareas, que facilitan la automatización del resto de tareas del proyecto: instalación de dependencias, ejecución de tests, compil
Tienes que exponer primero los criterios que vas a usar para elegir el gestor de tareas, como en la asignatura.

2023-03-14 16:41 UTC, JJ requested changes
Me da la impresión de que este PR se está yendo un poco del objetivo inicial. En todo caso, dale una vuelta, por favor. Va bien, quizás haya que completarlo.
También sería conveniente que aclararas siempre en los PRs el ámbito; por ejemplo, si quieres terminar la introducción aquí o solo comenzarla.

2023-03-14 16:41 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +historias y es reconocible por la audiencia. Un tropo puede ser una situación,
No sólo, puede ser tropo de títulos. Quizás "creación y presentación" sería más completo.

2023-03-14 16:41 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +constantemente creciendo.
Quizás sea importante que digas que es un wiki abierto; las páginas no son estáticas.

2023-03-14 16:41 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +actualmente, la cual ha cambiado bastante con el tiempo.
Quizás citar también la tesis, que está depositada en el DIGIBUG

2023-03-14 16:41 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +se quiere construir un scraper capaz de obtener de forma estructurada esta
REcuerda que siempre se menciona el problema antes que la solución. Resume aquí las historias de usuario, para que #1 sepa qué queremos solucionar y para quíen.

2023-03-14 16:41 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +información sobre tropos, ampliando aún más su funcionalidad para obtener tropos
Los problemas principales que tiene ya te los comenté
1. No funciona de forma incremental, de forma que cada vez hay que relanzar de nuevo el scrapre
2. No se mantiene al día con los cambios en la estructura del wikiç
3. No tiene un punto de partida (una araña) adecuado, como pone en los issues del módulo

"Ampliar más" no es muy preciso, por otro lado. Si planteas los problemas que quieres solucionar desde el principio, puedes dejar claro por dónde va a ir esa ampliación y a quién ayuda

2023-03-14 16:41 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +aritmética de contenidos no verbales, el análisis de tropos más usados en
Aclara esto; pon citas de word2vec y aclara qué se haría.

2023-03-14 16:41 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +La web de TvTropes, así como sus contenidos, está en constante cambio y la
"la web" ... "los contenidos". ¿Crees que sería mejor "la estructura" y "la estructura de las páginas y sus contenidos"?

2023-03-14 16:41 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ01} Estudiar las herramientas existentes que extraen o
REcuerda el documento que os pasé. No son lo mismo los objetivos y las tareas que tienes que llevar para alcanzarlas. Estudiar no es un objetivo, es algo que quieres hacer para alcanzar un objetivo; los objetivos tienen que estar en consonancia con el problema que quieres resolver.

2023-03-14 17:14 UTC, jlgallego99 commented
Dejamos este PR simplemente para lo de los últimos commits? Que era la idea que tenía: arreglar lo de las líneas de latex y añadir el gestor de tareas con las tareas básicas y su justificación, e implemento las mejoras que me has comentado en otro PR de la rama milestone0 que pretenderá cerrar capítulos de la documentación como tal
Este PR surgió de que tenía un PR pendiente de la otra rama y quise ponerme a desarrollar lo del gestor de tareas paralelamente sin pisar esa rama

2023-03-22 17:56 UTC, JJ approved these changes
Sí, mejor lo fusionas, porque estoy revisando de nuevo cosas que ya están aquí...

2023-03-22 18:46 UTC, merged