Fin Milestone 0 - Capitulos 1, 2, 3 y 4
jlgallego99/TropesToGo pull request #31
Opened 2023-03-21 20:14 UTC by jlgallego99

Con este PR se pretende terminar el Milestone 0, cerrando los issues que quedan y teniendo completados los cuatro primeros capítulos de la documentación:

- **Capítulo 1: Introducción**: Contexto del trabajo, el problema principal y secciones que tiene. Especificar la terminología de tropos y distintas definiciones básicas (closes #12)
- **Capítulo 2: Descripción del problema**: Descripción del problema, como se pretende resolver y los objetivos que quiere tener el trabajo al final, relacionados con los problemas descritos (closes #29)
- **Capítulo 3: Estado del arte**: Descripción de los elementos principales del dominio del problema y trabajos relacionados (closes #5). Justificación de lenguaje de programación y herramientas software de testing, scraping, CI y tareas (closes #26)
- **Capítulo 4: Planificación**: Introducción a la ingeniería del software, metodología que se va a usar, planificación y explicación del proceso de seguimiento del desarrollo (closes #11). Estudio de los usuarios objetivo e historias de usuario asociadas (closes #4)

2023-03-22 16:38 UTC, JJ commented
Cuando un PR sale tan tocho, es casi siempre mejor dividirlo en varios...
Es más fácil para quien lo hace y quien lo revisa. Le echaré un vistazo de todas formas.

2023-03-22 16:55 UTC, JJ requested changes
El principal problema aquí es la formulación de los objetivos; a la vez, si reformulas los objetivos en el dominio del problema, tienes que reciclar los viejos "objetivos" como o requisitos funcionales (algunos lo serán directamente) o productos mínimamente viables (quiero una araña, un scraper, un scraper que sea capaz de identificar metadatos)

2023-03-22 16:55 UTC, JJ commented on doc/bibliografia.bib
> +title = {Practical Web Scraping for Data Science: Best Practices and Examples with Python},
Recuerda "proteger" las mayúsculas "reales" con {} para que no te las elimine en el texto generado; LaTeX pasa todo a minúsculas si no

2023-03-22 16:55 UTC, JJ commented on doc/bibliografia.bib
> +	title = {16 {Amazing} {Agile} {Statistics} [2023]: {What} {Companies} {Use} {Agile} {Methodology} – {Zippia}},
¿Ves? Estas están protegidas, aunque quizás se han pasado un poco (y para el caso, podían haber puesto doble llave alrededor de toda la cita.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +convenciones llamados \textit{tropos}, o recursos reiterativos, que tienen un
En realidad, nadie los llama tropos, como viste. Di mejor "llamaremos"

2023-03-22 16:55 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +motivo, cuya definición es: ``En arte, rasgo característico que se repite en una
no estoy seguro que "motivo" sea la traducción adecuada de "motif".

Usa también el entorno adecuado para citas, `verbatim` por ejemplo.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +obra o en un conjunto de ellas`` (Real Academia Española, 2023, definición 3).
El IDE que estás usando no cambia como debiera las dos comillas invertidas finales a comillas invertidas en el otro sentido; por eso aparece el resto del párrafo como si siguiera las comillas. Usa algún IDE para trabajar con LaTeX, o un modo adecuado. Emacs va bastante bien.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +historia, de forma que no la interrumpa (en cuyo caso, sería un cliché) sino que
Recuerda que puede ser también presentar o publicar la historia. Los títulos de Star Wars son un tropo, por ejemplo, o el presentar una escena con un personaje al lado de los títulos de crédito donde dicen quién es.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +TvTropes\footnote{\url{https://tvtropes.org/}} es una wiki abierta con contenido
Pon el pie de página la primera vez que lo menciones.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Esta información no está estructurada y, por tanto, no existe una manera de
En las características de la web, recuerda hacer énfasis en que el contenido puede variar, dado que es un wiki.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +en constante cambio, con contenidos como las fechas que no están estructurados y
OK, aquí lo dices, pero explica que es porque se trata de un wiki, y cómo son los cambios: pueden aparecer tropos nuevos, pelis nuevas, o cambios en las pelis existentes.
Quizás aquí sería interesante que miraras a ver cuantos cambios hay y con qué frecuencia; eso puede justificar con qué frecuencia lances la araña más adelante (además de que el dato aquí es relevante)

2023-03-22 16:55 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Por tanto, el propósito de este TFM es el de construir un \textit{scraper} que
El propósito es siempre solucionar un problema. Lo que vas a hacer es un scraper, pero tienes que expresar claramente el propósito.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ02} El \textit{scraper} desarrollado debe dar la
No está en el dominio del problema.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ03} El \textit{scraper} debe ser capaz de actualizar la
Si lo está, pero estás mencionando la solución, lo que lo hace impreciso.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ04} Se busca desarrollar un \textit{scraper} eficiente que
Una vez más, dominio del problema, pero menciona la solución, lo que implica quedarse ya con una solución específica al problema. Esto pide un scraper "rápido", pero si mencionas sólo el problema (hay una gran cantidad de datos y/o cambian con mucha frecuencia) la solución puede ser trabajar con una caché local o a diferentes niveles.

2023-03-22 16:55 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ05} El \textit{scraper} debe ser capaz de extraer
Una vez más, descríbelo en el dominio del problema.

2023-03-24 06:38 UTC, JJ requested changes
Tendrías que darle todavía una vuelta a los objetivos.

2023-03-24 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +información secundaria sobre los contenidos audiovisuales que tienen, los cuales
Añade un ejemplo: un resumen, o la lista de actores o el director. Aquí se trata de justificar principalmente por qué habría que extraer los metadatos con el objetivo de identificarlos en otras BDs que sí los tengan.

2023-03-24 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +estructurada y se encuentra dentro de un texto pensado solo para ser entendible
A veces directamente no está.

2023-03-24 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Por tanto, el propósito de este TFM es el de aportar una solución informática a
quizás añadir "sostenible", en el sentido que detecte cuando haya cambios de estructura que invaliden el scraper; actualmente no lo tiene

2023-03-24 06:38 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +cambio, varias páginas están estructuradas de distintas maneras, algunas usando
"páginas de temas diferentes" o "páginas diferentes". Quizás añadir un ejemplo.

2023-03-24 06:38 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +problemas el \textit{scraper} debe conocer de antemano todas las estructuras que
Igual esto es mucho detalle para una introducción; hay que dejar algo para la implementación.

2023-03-24 06:38 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ02} Diseñar y desarrollar una araña que sea capaz de
Estos dos objetivos son uno solo. Diferenciar entre scraper y araña no está en el dominio del problema. El problema es extraer información de todas las páginas.

2023-03-24 06:38 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ03} Diseñar y desarrollar una aplicación de línea de
Sigues mencionando la solución. Los objetivos están todos en el dominio del problema. Se trata de poder crear un sistema que pueda integrarse fácilmente en flujos de trabajo de machine learning. La solución será una línea de comandos, pero durante el desarrollo se te pueden ocurrir otras. 
En todo caso, sólo mencionar el problema permite saber si se ha solucionado. Si mencionas "diseñar una aplicación CLI" *cualquiera* que hagas va a cubrir ese objetivo.

2023-03-24 06:38 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ04} El \textit{scraper} entenderá la frecuencia con la que
NO menciones una solución concreta. Habla sólo de una "solución informática" o "aplicación"

2023-03-24 06:38 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ07} Los datos extraídos por el \textit{scraper} se
Esto es un detalle de implementación, no un objetivo.

2023-03-28 05:46 UTC, JJ approved these changes
En general, yo creo que está correcto, salvo detalles. :1st_place_medal:

2023-03-28 05:46 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +ser un wiki sobre \textit{tropos} que se utilizan para contar historias y demás
¿El objetivo no será más bien ser colaborativo y la implementación como wiki una forma de conseguirlo?

2023-03-28 05:46 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +no está estructurada y, por tanto, no existe una manera de acceder a ella
Puede no estar estructurada e incluso así tener API. Son dos cosas diferentes.

2023-03-28 05:46 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Por tanto, el propósito de este TFM es el de aportar una solución informática a
He visto que has añadido esto en la siguiente línea; lo habitual en este caso es comentar dónde se ha hecho y resolver.

2023-03-28 05:46 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +La estructura entre diferentes páginas de TvTropes, así como sus contenidos,
"relación" o "enlaces", ¿no?

2023-03-28 05:46 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +En general, todas las páginas presentan una serie de distintas estructuras para
Creo que tendrías que mirar algún sinónimo de estructuras...

2023-03-28 05:46 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +organizar la misma información sin demasiado aviso, y es algo que se tiene que
¿"sin demasiado aviso"?

2023-03-28 05:46 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +tener en cuenta en todo momento. Existen una serie de tipos principales que
¿"patrones principales"?

2023-03-28 05:46 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    metadatos no estructurada, aparte de los \textit{tropos}, que permita poder
La información no es "no estructurada", es el contenido del que se extrae

2023-03-28 16:14 UTC, jlgallego99 commented on doc/secciones/02_descripcion.tex
> +organizar la misma información sin demasiado aviso, y es algo que se tiene que
Quería decir que no se sabe de antemano qué forma puede tomar una página, pero lo he expresado bastante mal

2023-03-28 16:18 UTC, jlgallego99 commented on doc/secciones/02_descripcion.tex
> +tener en cuenta en todo momento. Existen una serie de tipos principales que
Las formas más comunes de una pagina en TvTropes, lo expresaré de otra manera para que se entienda mejor

2023-03-30 16:12 UTC, merged