Entorno de tests en Docker y flujos de CI para subirlo y ejecutar los tests
jlgallego99/TropesToGo pull request #63
Opened 2023-05-11 18:48 UTC by jlgallego99

Este PR está orientado a añadir lo necesario para automatizar la ejecución de los tests y poder empezar luego con el desarrollo, ya que en este milestone se empezará a programar código testeable, y se necesitan de flujos que automaticen las pruebas

Se crea un Dockerfile que define un contenedor docker ligero con el proyecto y lo necesario para poder ejecutar sus tests: el lenguaje Go y el task runner Mask. Este contenedor se sube a Dockerfile mediante un Action, que permitirá poder acceder al contenedor desde cualquier lugar de forma online (closes #62)
Se define otro flujo de CI encargado de automatizar la ejecución de tests, accediendo al contenedor anteriormente creado en Dockerhub, de forma que los tests se pasen en un entorno aislado y controlado cada vez que se haga push a master, controlando que todo el código que esté en master esté testeado (closes #61)

2023-05-15 17:28 UTC, JJ requested changes
Los dos workflows tienen bastante código en común; DRY: salvo que veas imprescindible que se ejecuten en paralelo para ahorrar tiempo, los dos son claramente dependientes uno de otro y deberían ser steps de un mismo job, o en todo caso dos jobs.

2023-05-15 18:50 UTC, JJ requested changes
No entiendo muy bien para qué sirve el Dockerfile. Si lo vas a crear, sería mejor que hicieras un workflow específico para que se generara cada vez que que cambiara. Pero no creo que haga falta; como producto mínimamente viable creo que con el workflow que has hecho, si no tarda mucho, es suficiente.

Aparte, cualifica un poco los paths para que se lance el workflow, e incluye también pull rquests.

2023-05-15 18:50 UTC, JJ commented on Dockerfile
> +    && source $HOME/.cargo/env \
Repetido

2023-05-15 18:50 UTC, JJ commented on Dockerfile
> +    && curl https://sh.rustup.rs -sSf | bash -s -- -y \
Haz con privilegios sólo aquellos que lo necesiten

2023-05-15 18:51 UTC, JJ commented on Dockerfile
> +    && curl https://sh.rustup.rs -sSf | bash -s -- -y \
En todo caso, no sé si lo mejor será no usar el Dockerfile, visto lo visto.

2023-05-15 18:59 UTC, jlgallego99 commented
El dockerfile estaba porque al principio estaba haciendo que el testing se hiciese dentro del contenedor, pero al final he decidido que no como habiamos hablado y he puesto en los commits. Se me habia olvidado borrar el Dockerfile, pero ya lo he eliminado
Y no entiendo muy bien que quieres con que cualifique los paths e incluya pull requests

2023-05-15 19:03 UTC, JJ commented
> El dockerfile estaba porque al principio estaba haciendo que el testing se hiciese dentro del contenedor, pero al final he decidido que no como habiamos hablado y he puesto en los commits. Se me habia olvidado borrar el Dockerfile, pero ya lo he eliminado Y no entiendo muy bien que quieres con que cualifique los paths e incluya pull requests

Lo primero, para que sólo compile cuando estés con el código, no con la memoria o el README. Lo segundo, porque no es descartable que te hagan un PR (yo te lo puedo hacer) y en ese caso no ejecutaría los tests hasta que no hagas push a main.

2023-05-17 08:13 UTC, JJ approved these changes
Ninguno de las observaciones bloquea nada, así que p'alante.

2023-05-17 08:13 UTC, JJ commented on .github/workflows/build-test-go.yml
> +      - '**.go'
Mira bien los paths y su expresión. Creo que lo que quieres hacer aquí es `**/*.go`. Es probable que esto funcione simplemente porque `**.go` es lo mismo que `*.go` pero la forma más adecuada de hacerlo sería esa.
Aparte, igual deberías poner simplemente el directorio donde esté el código; más adelante puedes lanzar un error si se pone un .go en otro directorio, pero por ahora vale como PMV

2023-05-17 08:13 UTC, JJ commented on .github/workflows/build-test-go.yml
> +    buildandtest:
naming nit: usa `-` (kebab case) para separar palabras; eso o `snake_case`

2023-05-17 08:13 UTC, JJ commented on .github/workflows/build-test-go.yml
> +                go-version: '1.20'
Como PMV, una vez más, vale, pero recuerda lo que os dije sobre la matriz de comprobación de versiones.

2023-05-17 15:46 UTC, merged