Implementación de repositorios JSON y CSV para almacenar la extracción de tropos
jlgallego99/TropesToGo pull request #74
Opened 2023-06-07 17:45 UTC by jlgallego99

Este PR depende de resolver el anterior #73 en el que se desarrolla la primera versión del scraper. Con este PR se expande, añadiendo los repositorios donde escribir los datos extraídos en datasets de distintos formatos

Se implementa la interfaz repositorio de Media para crear dos datasets distintos: uno de JSON y otro de CSV, pudiendo añadir peliculas y modificarlas, ya que en TvTropes la informacion va a estar en constante cambio y se tiene que tener en cuenta (closes #68 closes #21)

2023-06-12 12:49 UTC, JJ requested changes
Estoy a mitad de camino y el principal problema que veo aquí es que no estás justificando porqué quieres las diferentes implementaciones, y sobre todo por qué estás implementando acceso concurrente a las mismas. Para resolver #21 (y para cualquier otra cosa) siempre hay que buscar la solución lo más simple posible, y yo creo en este caso podrías considerar una con un par de características
1. Un interfaz abstracto a la persistencia de datos, que permita tanto actualización de datos como crearlos desde 0, o borrarlos.
2. Una implementación lo más simple posible, pero en todo caso oculta al usuario, que permita hacer esas cosas.

Recuerda que un principio importante para reducir deuda técnica es separar el interfaz de la implementación; con la implementación doble de JSON y de CSV no sólo estás acoplando fuertemente una y otra, sino que además cuaquier clase que los implemente tendrá que ser consciente de cuál es la implementación, sin poder usar uno u otro de forma intercambiable (el célebre principio de sustitución de Liskov)

2023-06-12 12:49 UTC, JJ commented on .gitignore
> +tropestogo/.idea/*
Con que pongas .idea/ ya lo ignora en cualquier posición

2023-06-12 12:49 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	sync.Mutex
Encontrar esto aquí despista un poco, y más apuntando el commit directamente a #68, que sólo habla de almacenar los datos. Da la impresión de que es un problema de implementación (que haya que escribir a la vez desde diferentes hebras o algo así), pero no está explicitado, y en todo caso no parece un producto mínimamente viable. Así que sería conveniente que explicaras minimamente el problema ligado a #68 en un issue (y por supuesto comprobaras con un test que funciona como debe) o bien simplemente usa una estructura simple que responda mínimamente a lo que se solicita.

2023-06-12 12:49 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	ErrFileNotExists   = errors.New("CSV dataset file does not exist")
No sé cuales son las mejores prácticas en diseño de errores de Go, pero en casi todos los casos se trata de crear un error parametrizado de forma que sea fácil recuperarse del mismo. En este caso, por ejemplo, ¿de qué fichero estamos hablando? ¿Cuando veas eso en un error y pete el programa, te va a ayudar a algo?

2023-06-12 12:49 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	ErrDuplicatedMedia = errors.New("duplicated media: the record already exists on the dataset")
Exactamente igual. Normalmente los errores tienen dos partes: creación del mismo, y luego conversión en cadena. Conviene que los separes, y veas que realmente crear un error con un mensaje genérico no añade mucho valor al cliente sobre simplemente levantar ese error.

2023-06-12 12:49 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	repository.Lock()
En este momento el único que puede tener el handle es esta función. Si otra parte del progrma (¿la hay?) trata de abrir un fichero con el mismo math, ¿qué va a suceder? ¿Va a haber un problema de interlock?

2023-06-12 12:49 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +func (repository *CSVRepository) GetDelimiter() rune {
¿Qué HU necesita esto?
Crea sólo las funciones que hagan falta, ni una más ni una menos.

2023-06-12 12:49 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +		return nil, err
¿No miras qué error es y devuelves un error propio adecuado?

2023-06-12 12:49 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	if errReadCSV != nil {
No suele ser una buena idea "burbujear" los errores de bajo nivel hacia arriba. En general, no van a ser capaces de hacer nada con ellos. Trata de examinar los errores, mira a ver si se pueden recuperar o no, y en caso de que no sea posible tira un error genérico, pero siempre propio.

2023-06-12 12:49 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +func (repository *CSVRepository) UpdateMedia(title string, year string, media media.Media) error {
¿No has considerado crear un interfaz común a cualquier almacenamiento de datos? Sólo la implementación debería preocuparse si se trata o no de CSV, JSON o una base de datos.
En todo caso, estás tomando la decisión de actualizar cada vez que se encuentre un título, y no estoy seguro de que sea la más adecuada. En general, tanto CSV como JSON deberían actualizarse sólo cuando se abra o cierre la aplicación.  Si hubiera varios "scrapers" trabajando a la vez, esto podría ser lo razonable, pero una vez más, no es el producto mínimamente viable (y no hay una HU que lo pida). En todo caso, trabajar ahora con un lector/escritor de CSV simple (y de JSON) con un interfaz común facilitará más adelante la refactorización.
En ese sentido, deberías haber cualificado un poco más #21 para ver realmente qué es necesario en cada una de las etapas.

2023-06-12 14:46 UTC, jlgallego99 commented
Quitaré por lo pronto la concurrencia, pero además de eso como podría simplificarlo más? La interfaz abstracta y la implementación ya las tengo. En #68 indico que se deberia implementar al menos 2 repositorios precisamente para mostrar el hecho de que la interfaz del repositorio se puede implementar para distintos datasets, y CSV y JSON son los formatos más comunes. Los tengo separados en dos modulos distintos y se pueden usar igual de forma intercambiable, de hecho en los tests del scraper se puede ver que ambos se utilizan de igual forma: se definen como variables tipo Repositorio y el scraper llama a la funcion AddMedia al hacer scraping, independientemente del repositorio que tenga configurado. Debería solo implementar uno de ellos entonces?

2023-06-12 14:48 UTC, jlgallego99 commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	ErrFileNotExists   = errors.New("CSV dataset file does not exist")
Le añadiré información sobre el nombre de fichero y la ruta para saber mejor qué está fallando

2023-06-12 15:00 UTC, jlgallego99 commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	repository.Lock()
No había tenido en cuenta que podrían surgir bastantes problemas de añadir los cerrojos, así que tiene sentido dejarlos para más adelante porque surgen varios problemas y aún no se si son del todos necesarios

2023-06-12 15:07 UTC, jlgallego99 commented on tropestogo/media/csv_dataset/csv_dataset.go
> +		return nil, err
No lo miro porque según la documentación el error, si hay, es siempre el mismo: un PathError. Lo que si puedo hacer es devolver uno propio sumado al que me devuelve

2023-06-12 15:13 UTC, jlgallego99 commented on tropestogo/media/csv_dataset/csv_dataset.go
> +func (repository *CSVRepository) UpdateMedia(title string, year string, media media.Media) error {
Claro, la interfaz común ya se tiene, es el RepositoryMedia y luego cada struct implementa los metodos para cada formato de datos. UpdateMedia es uno de los metodos definidos en el interfaz comun. Creo que no nos estamos entendiendo bien porque lo que dices es justo lo que he hecho
Con respecto a la actualización, la idea de este método es solo llamarse para registros concretos, por ejemplo cuando se vuelva a scrapear todo TvTropes y se vea que una pagina ha cambiado, entonces llamar al UpdateMedia y cambiar ese registro concreto

2023-06-13 12:16 UTC, JJ commented on tropestogo/media/json_dataset/json_dataset.go
> +func Error(message string, err error, subErr error) error {
En realidad deberías incluir metadatos en los errores, como te digo para que haya alguna forma de recuperarse de los mismos, y no simplemente petar. Como versión inicial vale.

2023-06-13 12:17 UTC, JJ commented on tropestogo/media/json_dataset/json_dataset_test.go
> +			updatedUrl, _ := url.Parse("https://tvtropes.org/pmwiki/pmwiki.php/Film/Oldboy2013")
A menos que lo que quieras realmente es probar que este URL específico funciona bien (lo que no haría cada tes), es fuertemente desaconsejable que uses recursos online para hacer tests.

2023-06-14 11:32 UTC, JJ requested changes
Si no me equivoco, el recurso sigue estando online, ¿no?

2023-06-14 11:32 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	ErrFileNotExists   = errors.New("CSV dataset file does not exist")
¿En otro PR?

2023-06-14 11:32 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset_test.go
> +		It("Shouldn't exist a CSV file", func() {
Grammar: subject before vert "A CSV file shoudn't exist"

2023-06-14 11:32 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset_test.go
> +		It("Shouldn't exist a CSV file", func() {
"o should not be present"

2023-06-14 11:32 UTC, JJ commented on tropestogo/media/json_dataset/json_dataset.go
> +func (repository *JSONRepository) UpdateMedia(title string, year string, med media.Media) error {
Código limpio: los nombres de las variables deberían ser poco (o nada) ambiguos. (como `med`)

2023-06-14 11:44 UTC, jlgallego99 commented
No lo está, por que? En el scraper_test se puede ver que lo que se hace es un os.Open para abrir el fichero HTML en memoria. Lo que sí hago es también indicar la URL de la página donde debería estar, pero simplemente se trata como string para hacer comprobaciones, no se hace ninguna peticion ni se usan recursos online

2023-06-14 11:57 UTC, JJ commented
> No lo está, por que? En el scraper_test se puede ver que lo que se hace es un os.Open para abrir el fichero HTML en memoria. Lo que sí hago es también indicar la URL de la página donde debería estar, pero simplemente se trata como string para hacer comprobaciones, no se hace ninguna peticion ni se usan recursos online

Queda un poco confuso, la verdad... Un URI es un URI, y si corresponde a un URL, debería usarse como tal.

2023-06-14 12:01 UTC, jlgallego99 commented
Yo uso el URL completo, no un URI, es imprescindible para las comprobaciones (ver que la pagina es efectivamente de tvtropes) y para sacar alguna informacion basica, por eso va de la mano con el HTML. Cuando se hace una peticion, se hace desde la entidad Page, que es un struct del codigo. No se como podria hacerlo menos confuso

2023-06-14 12:05 UTC, jlgallego99 commented
Supongo que te refieres a que recibo un objeto URL pero unicamente lo trato como string y no hago peticiones con él no? En ese caso lo cambio a pasarlo como string entonces

2023-06-14 12:14 UTC, JJ requested changes
OK, ya lo veo un poco mejor, pero veo un problema
1. Estás siempre usando el mismo URL, y no lo has creado como una constante
2. Si lo que quieres es testear si se reconocen correctamente el formato del URL, deberías descargarte varios en un fichero, o como veas, y testearlos, con diferentes variaciones y posibilidades, a ver si todos los reconoce.
3. No entiendo muy bien porqué usas "Page" y no la convención para constructor, que sería algo así como NewPage, ¿no? estás usando dos pasos, uno parsear el URL y dos llamar al "constructor", en vez de uno solo. 
4. Tendrías que replantearte el objeto valor que estás usando aquí. En general, tener una estructura que agrupe un valor inmutable (URL o URL parseado) y un resultado de una operación (última actualización) no es una buena idea, porque te obliga a buscar secuencialmente un objeto para acceder al valor. Si *siempre* vas a comprobar todas las pelis una por una para nuevos trops, sería la forma adecuada, pero si lo que vas a hacer es consultar una página de cambios y acceder por URL, tienes que relacionar URL con última modificación en una entidad, que tenga control de ambos, y que permita del primero acceder al segundo.

Así que creo que, en este caso, deberías forkear esta rama y trabajar exclusivamente en ese aspecto, porque este PR tiene 20 ficheros y creo qeu eso merece un poco de atención aparte.

2023-06-14 12:14 UTC, JJ commented on .gitignore
> +tropestogo/.idea/*
:arrow_up:

2023-06-14 12:14 UTC, JJ commented on tropestogo/service/scraper/scraper.go
> +// CheckIsWorkPage checks if the received page belongs to a tvtropes.org Work page
Recuerda usar sólo docstrings, no comentarios inline

2023-06-14 12:14 UTC, JJ commented on tropestogo/service/scraper/scraper.go
>  	// First check if the domain is TvTropes
La variable se llama tvTropesURL. Si tienes que comprobar si lo es efectivamente o no, el nombre no corresponde al contenido.

2023-06-14 12:14 UTC, JJ commented on tropestogo/media/json_dataset/json_dataset_test.go
> +			updatedUrl, _ := url.Parse("https://tvtropes.org/pmwiki/pmwiki.php/Film/Oldboy2013")
OK, creo que lo estoy entendiendo mejor ahora, no estás descargándote esa página, sino que estás testeando los URLs de por sí.

2023-06-14 13:36 UTC, jlgallego99 commented on tropestogo/service/scraper/scraper.go
> +// CheckIsWorkPage checks if the received page belongs to a tvtropes.org Work page
Pero este no es inline, no? A mi me aparece en la línea anterior a la funcion

2023-06-14 13:39 UTC, jlgallego99 commented on tropestogo/media/csv_dataset/csv_dataset.go
> +	ErrFileNotExists   = errors.New("CSV dataset file does not exist")
En este commit se ha hecho https://github.com/jlgallego99/TropesToGo/pull/74/commits/62a204e89940473cdc81b32e5dba6c6beef88a0d

2023-06-14 14:36 UTC, JJ commented on tropestogo/service/scraper/scraper.go
> +// CheckIsWorkPage checks if the received page belongs to a tvtropes.org Work page
No, pero tienes que ponerlo en formato docstring, con los parámetros de la función o el formato que se siga en Go

2023-06-14 15:06 UTC, jlgallego99 commented on tropestogo/service/scraper/scraper.go
> +// CheckIsWorkPage checks if the received page belongs to a tvtropes.org Work page
Ya hablamos esto, en Go los comentarios son así, un comentario normal sin parámetros ni nada legible por máquinas, simplemente "buenos comentarios" como pone en https://go.dev/blog/godoc
Aunque supongo que te refieres a que deberia especificar más qué recibe y qué devuelve y hacer el comentario más explicativo, arreglaré eso entonces

2023-06-15 15:36 UTC, JJ approved these changes
Mejor aprobar y seguir más adelante si hay algún problema de detalle.

2023-06-15 15:36 UTC, JJ commented on tropestogo/media/csv_dataset/csv_dataset_test.go
> +			Expect(len(records[0])).To(Equal(7))
Te digo lo de siempre de los literales. No se deben usar. Hacen muy complicada la refactorización. Trata de no usarlos en el futuro.

2023-06-15 18:37 UTC, merged